# -*- coding: utf-8 -*-

"""Reference data used in index creation."""

# Lang mapping to ISO 639-1 (from ISO 639-2 or anyting else)
# for all commonly known languaes.
# Source: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
LANG_MAP = {
    "aar": "aa",
    "abk": "ab",
    "ave": "ae",
    "afr": "af",
    "aka": "ak",
    "amh": "am",
    "arg": "an",
    "ara": "ar",
    "asm": "as",
    "ava": "av",
    "aym": "ay",
    "aze": "az",
    "bak": "ba",
    "bel": "be",
    "bul": "bg",
    "bih": "bh",
    "bis": "bi",
    "bam": "bm",
    "ben": "bn",
    "bod": "bo",
    "tib": "bo",
    "bre": "br",
    "bos": "bs",
    "cat": "ca",
    "che": "ce",
    "cha": "ch",
    "cos": "co",
    "cre": "cr",
    "ces": "cs",
    "cze": "cs",
    "chu": "cu",
    "chv": "cv",
    "cym": "cy",
    "wel": "cy",
    "dan": "da",
    "deu": "de",
    "ger": "de",
    "div": "dv",
    "dzo": "dz",
    "ewe": "ee",
    "ell": "el",
    "gre": "el",
    "eng": "en",
    "epo": "eo",
    "spa": "es",
    "est": "et",
    "eus": "eu",
    "baq": "eu",
    "fas": "fa",
    "per": "fa",
    "ful": "ff",
    "fin": "fi",
    "fij": "fj",
    "fao": "fo",
    "fra": "fr",
    "fre": "fr",
    "fry": "fy",
    "gle": "ga",
    "gla": "gd",
    "glg": "gl",
    "grn": "gn",
    "guj": "gu",
    "glv": "gv",
    "hau": "ha",
    "heb": "he",
    "hin": "hi",
    "hmo": "ho",
    "hrv": "hr",
    "hat": "ht",
    "hun": "hu",
    "hye": "hy",
    "arm": "hy",
    "her": "hz",
    "ina": "ia",
    "ind": "id",
    "ile": "ie",
    "ibo": "ig",
    "iii": "ii",
    "ipk": "ik",
    "ido": "io",
    "isl": "is",
    "ice": "is",
    "ita": "it",
    "itl": "it",
    "iku": "iu",
    "jpn": "ja",
    "jav": "jv",
    "kat": "ka",
    "geo": "ka",
    "kon": "kg",
    "kik": "ki",
    "kua": "kj",
    "kaz": "kk",
    "kal": "kl",
    "khm": "km",
    "kan": "kn",
    "kor": "ko",
    "kau": "kr",
    "kas": "ks",
    "kur": "ku",
    "kom": "kv",
    "cor": "kw",
    "kir": "ky",
    "lat": "la",
    "ltz": "lb",
    "lug": "lg",
    "lim": "li",
    "lin": "ln",
    "lao": "lo",
    "lit": "lt",
    "lub": "lu",
    "lav": "lv",
    "mlg": "mg",
    "mah": "mh",
    "mri": "mi",
    "mao": "mi",
    "mkd": "mk",
    "mac": "mk",
    "mal": "ml",
    "mon": "mn",
    "mar": "mr",
    "msa": "ms",
    "may": "ms",
    "mlt": "mt",
    "mya": "my",
    "bur": "my",
    "nau": "na",
    "nob": "nb",
    "nde": "nd",
    "nep": "ne",
    "ndo": "ng",
    "nld": "nl",
    "dut": "nl",
    "nno": "nn",
    "nor": "no",
    "nbl": "nr",
    "nav": "nv",
    "nya": "ny",
    "oci": "oc",
    "oji": "oj",
    "orm": "om",
    "ori": "or",
    "oss": "os",
    "pan": "pa",
    "pli": "pi",
    "pol": "pl",
    "pus": "ps",
    "por": "pt",
    "que": "qu",
    "roh": "rm",
    "run": "rn",
    "ron": "ro",
    "rum": "ro",
    "rus": "ru",
    "kin": "rw",
    "san": "sa",
    "srd": "sc",
    "snd": "sd",
    "sme": "se",
    "sag": "sg",
    "sin": "si",
    "slk": "sk",
    "slo": "sk",
    "slv": "sl",
    "smo": "sm",
    "sna": "sn",
    "som": "so",
    "sqi": "sq",
    "alb": "sq",
    "srp": "sr",
    "ssw": "ss",
    "sot": "st",
    "sun": "su",
    "swe": "sv",
    "swa": "sw",
    "tam": "ta",
    "tel": "te",
    "tgk": "tg",
    "tha": "th",
    "tir": "ti",
    "tuk": "tk",
    "tgl": "tl",
    "tsn": "tn",
    "ton": "to",
    "tur": "tr",
    "tso": "ts",
    "tat": "tt",
    "twi": "tw",
    "tah": "ty",
    "uig": "ug",
    "ukr": "uk",
    "urd": "ur",
    "uzb": "uz",
    "ven": "ve",
    "vie": "vi",
    "vol": "vo",
    "wln": "wa",
    "wol": "wo",
    "xho": "xh",
    "yid": "yi",
    "yor": "yo",
    "zha": "za",
    "zho": "zh",
    "chi": "zh",
    "zul": "zu"
    }


# Language fields by ISO 639-1 codes.
LANG_FIELDS = {
    "en": {"type": "text", "analyzer": "english"},
    "cz": {"type": "text", "analyzer": "czech"},
    "gr": {"type": "text", "analyzer": "greek"},
    "es": {"type": "text", "analyzer": "spanish"},
    "fi": {"type": "text", "analyzer": "finnish"},
    "it": {"type": "text", "analyzer": "italian"},
    "lv": {"type": "text", "analyzer": "latvian"},
    "ar": {"type": "text", "analyzer": "arabic"},
    "hy": {"type": "text", "analyzer": "armenian"},
    "eu": {"type": "text", "analyzer": "basque"},
    "bn": {"type": "text", "analyzer": "bengali"},
    "bg": {"type": "text", "analyzer": "bulgarian"},
    "ca": {"type": "text", "analyzer": "catalan"},
    "nl": {"type": "text", "analyzer": "dutch"},
    "fr": {"type": "text", "analyzer": "french"},
    "gl": {"type": "text", "analyzer": "galician"},
    "de": {"type": "text", "analyzer": "german"},
    "hi": {"type": "text", "analyzer": "hindi"},
    "hu": {"type": "text", "analyzer": "hungarian"},
    "id": {"type": "text", "analyzer": "indonesian"},
    "ga": {"type": "text", "analyzer": "irish"},
    "lt": {"type": "text", "analyzer": "lithuanian"},
    "nb": {"type": "text", "analyzer": "norwegian"},
    "pt": {"type": "text", "analyzer": "portuguese"},
    "ro": {"type": "text", "analyzer": "romanian"},
    "ru": {"type": "text", "analyzer": "russian"},
    "ku": {"type": "text", "analyzer": "sorani"},
    "cv": {"type": "text", "analyzer": "swedish"},
    "tr": {"type": "text", "analyzer": "turkish"}
    }
